package Model;
// Generated Oct 15, 2019 2:26:15 PM by Hibernate Tools 4.3.1



/**
 * Administrator generated by hbm2java
 */
public class Administrator  implements java.io.Serializable {


     private Integer maAdmin;
     private String accountAdmin;
     private String passwordAdmin;

    public Administrator() {
    }

    public Administrator(String accountAdmin, String passwordAdmin) {
       this.accountAdmin = accountAdmin;
       this.passwordAdmin = passwordAdmin;
    }
   
    public Integer getMaAdmin() {
        return this.maAdmin;
    }
    
    public void setMaAdmin(Integer maAdmin) {
        this.maAdmin = maAdmin;
    }
    public String getAccountAdmin() {
        return this.accountAdmin;
    }
    
    public void setAccountAdmin(String accountAdmin) {
        this.accountAdmin = accountAdmin;
    }
    public String getPasswordAdmin() {
        return this.passwordAdmin;
    }
    
    public void setPasswordAdmin(String passwordAdmin) {
        this.passwordAdmin = passwordAdmin;
    }




}


