package Model;
// Generated Nov 6, 2019 9:03:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private Integer maNv;
     private String accountNv;
     private String passwordNv;
     private String tenNv;
     private String sdtnv;
     private String statusNv;
     private String ngaySinhNv;
     private Set<Phieumuon> phieumuons = new HashSet<Phieumuon>(0);

    public Nhanvien() {
    }

	
    public Nhanvien(String accountNv, String passwordNv, String tenNv, String statusNv) {
        this.accountNv = accountNv;
        this.passwordNv = passwordNv;
        this.tenNv = tenNv;
        this.statusNv = statusNv;
    }
    public Nhanvien(String accountNv, String passwordNv, String tenNv, String sdtnv, String statusNv, String ngaySinhNv, Set<Phieumuon> phieumuons) {
       this.accountNv = accountNv;
       this.passwordNv = passwordNv;
       this.tenNv = tenNv;
       this.sdtnv = sdtnv;
       this.statusNv = statusNv;
       this.ngaySinhNv = ngaySinhNv;
       this.phieumuons = phieumuons;
    }
   
    public Integer getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(Integer maNv) {
        this.maNv = maNv;
    }
    public String getAccountNv() {
        return this.accountNv;
    }
    
    public void setAccountNv(String accountNv) {
        this.accountNv = accountNv;
    }
    public String getPasswordNv() {
        return this.passwordNv;
    }
    
    public void setPasswordNv(String passwordNv) {
        this.passwordNv = passwordNv;
    }
    public String getTenNv() {
        return this.tenNv;
    }
    
    public void setTenNv(String tenNv) {
        this.tenNv = tenNv;
    }
    public String getSdtnv() {
        return this.sdtnv;
    }
    
    public void setSdtnv(String sdtnv) {
        this.sdtnv = sdtnv;
    }
    public String getStatusNv() {
        return this.statusNv;
    }
    
    public void setStatusNv(String statusNv) {
        this.statusNv = statusNv;
    }
    public String getNgaySinhNv() {
        return this.ngaySinhNv;
    }
    
    public void setNgaySinhNv(String ngaySinhNv) {
        this.ngaySinhNv = ngaySinhNv;
    }
    public Set<Phieumuon> getPhieumuons() {
        return this.phieumuons;
    }
    
    public void setPhieumuons(Set<Phieumuon> phieumuons) {
        this.phieumuons = phieumuons;
    }

    @Override
    public String toString()
    {
        return this.tenNv;
    }


}


