package Model;
// Generated Sep 23, 2019 3:42:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieumuon generated by hbm2java
 */
public class Phieumuon  implements java.io.Serializable {


     private Integer maPhieuMuon;
     private Khachhang khachhang;
     private Nhanvien nhanvien;
     private Sach sach;
     private Date ngayMuon;
     private Date hanTra;
     private Date ngayTra;
     private int soLuongMuon;
     private String tienBoiThuong;
     private String tienPhat;

    public Phieumuon() {
    }

	
    public Phieumuon(Khachhang khachhang, Nhanvien nhanvien, Sach sach, int soLuongMuon) {
        this.khachhang = khachhang;
        this.nhanvien = nhanvien;
        this.sach = sach;
        this.soLuongMuon = soLuongMuon;
    }
    public Phieumuon(Khachhang khachhang, Nhanvien nhanvien, Sach sach, Date ngayMuon, Date hanTra, Date ngayTra, int soLuongMuon, String tienBoiThuong, String tienPhat) {
       this.khachhang = khachhang;
       this.nhanvien = nhanvien;
       this.sach = sach;
       this.ngayMuon = ngayMuon;
       this.hanTra = hanTra;
       this.ngayTra = ngayTra;
       this.soLuongMuon = soLuongMuon;
       this.tienBoiThuong = tienBoiThuong;
       this.tienPhat = tienPhat;
    }
   
    public Integer getMaPhieuMuon() {
        return this.maPhieuMuon;
    }
    
    public void setMaPhieuMuon(Integer maPhieuMuon) {
        this.maPhieuMuon = maPhieuMuon;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }
    public Date getNgayMuon() {
        return this.ngayMuon;
    }
    
    public void setNgayMuon(Date ngayMuon) {
        this.ngayMuon = ngayMuon;
    }
    public Date getHanTra() {
        return this.hanTra;
    }
    
    public void setHanTra(Date hanTra) {
        this.hanTra = hanTra;
    }
    public Date getNgayTra() {
        return this.ngayTra;
    }
    
    public void setNgayTra(Date ngayTra) {
        this.ngayTra = ngayTra;
    }
    public int getSoLuongMuon() {
        return this.soLuongMuon;
    }
    
    public void setSoLuongMuon(int soLuongMuon) {
        this.soLuongMuon = soLuongMuon;
    }
    public String getTienBoiThuong() {
        return this.tienBoiThuong;
    }
    
    public void setTienBoiThuong(String tienBoiThuong) {
        this.tienBoiThuong = tienBoiThuong;
    }
    public String getTienPhat() {
        return this.tienPhat;
    }
    
    public void setTienPhat(String tienPhat) {
        this.tienPhat = tienPhat;
    }




}


