package Model;
// Generated Sep 23, 2019 3:42:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sach generated by hbm2java
 */
public class Sach  implements java.io.Serializable {


     private Integer maSach;
     private String tenSach;
     private String tenTacGia;
     private String nxb;
     private int soLuong;
     private String giaSach;
     private Set<Phieumuon> phieumuons = new HashSet<Phieumuon>(0);

    public Sach() {
    }

	
    public Sach(String tenSach, String tenTacGia, int soLuong, String giaSach) {
        this.tenSach = tenSach;
        this.tenTacGia = tenTacGia;
        this.soLuong = soLuong;
        this.giaSach = giaSach;
    }
    public Sach(String tenSach, String tenTacGia, String nxb, int soLuong, String giaSach) {
       this.tenSach = tenSach;
       this.tenTacGia = tenTacGia;
       this.nxb = nxb;
       this.soLuong = soLuong;
       this.giaSach = giaSach;
       
    }
    public Sach(String tenSach, String tenTacGia, String nxb, int soLuong, String giaSach, Set<Phieumuon> phieumuons) {
       this.tenSach = tenSach;
       this.tenTacGia = tenTacGia;
       this.nxb = nxb;
       this.soLuong = soLuong;
       this.giaSach = giaSach;
       this.phieumuons = phieumuons;
    }
   
    public Integer getMaSach() {
        return this.maSach;
    }
    
    public void setMaSach(Integer maSach) {
        this.maSach = maSach;
    }
    public String getTenSach() {
        return this.tenSach;
    }
    
    public void setTenSach(String tenSach) {
        this.tenSach = tenSach;
    }
    public String getTenTacGia() {
        return this.tenTacGia;
    }
    
    public void setTenTacGia(String tenTacGia) {
        this.tenTacGia = tenTacGia;
    }
    public String getNxb() {
        return this.nxb;
    }
    
    public void setNxb(String nxb) {
        this.nxb = nxb;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public String getGiaSach() {
        return this.giaSach;
    }
    
    public void setGiaSach(String giaSach) {
        this.giaSach = giaSach;
    }
    public Set<Phieumuon> getPhieumuons() {
        return this.phieumuons;
    }
    
    public void setPhieumuons(Set<Phieumuon> phieumuons) {
        this.phieumuons = phieumuons;
    }




}


